swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }

#when@dev:
#    # See https://symfony.com/doc/current/email/dev_environment.html
#    swiftmailer:
#        send all emails to a specific address
#        delivery_addresses: ['me@example.com']

when@test:
    swiftmailer:
        disable_delivery: true
