twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # deprecated - to be removed in Symfony 5.x
    exception_controller: null
